=== NexaiYlia/xml_task2/src/main/resources/flowers.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/flowers"
        xmlns:tns="http://www.example.org/flowers"
        elementFormDefault="qualified">

    <element name="flowers">
        <complexType>
            <sequence>
                <element ref="tns:flower" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

    <element name="flower" type="tns:Flower-type" abstract="true"/>
    <element name="rose" type="tns:Rose-type" substitutionGroup="tns:flower"/>
    <element name="pion" type="tns:Pion-type" substitutionGroup="tns:flower"/>
    <element name="rhododendron" type="tns:Rhododendron-type" substitutionGroup="tns:flower"/>
    <element name="orchid" type="tns:Orchid-type" substitutionGroup="tns:flower"/>

    <complexType name="Flower-type">
        <sequence>
            <element name="name">
                <simpleType>
                    <restriction base="string">
                        <minLength value="3"/>
                        <maxLength value="30"/>
                    </restriction>
                </simpleType>
            </element>
            <element name="date-of-planting" type="tns:Date-of-planting"/>
            <element name="soil" type="tns:Soil"/>
            <element name="origin" type="string"/>
            <element name="visual-parameters" type="tns:Visual-parameters"/>
            <element name="growing-tips" type="tns:Growing-tips"/>
            <element name="multiplying" type="tns:Multiplying"/>
        </sequence>
        <attribute name="id" type="tns:Id" use="required"/>
    </complexType>

    <complexType name="Rose-type" >
        <complexContent>
            <extension base="tns:Flower-type">
                <sequence>
                <element name="spikes" type="boolean"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>


    <complexType name="Pion-type" >
        <complexContent>
            <extension base="tns:Flower-type">
                <sequence>
                    <element name="number-peduncles" type="int" />
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="Rhododendron-type" >
        <complexContent>
            <extension base="tns:Flower-type">
                <sequence>
                    <element name="stem-thickness" type="double" />
                </sequence>
            </extension>
        </complexContent>
    </complexType>


    <complexType name="Orchid-type">
        <complexContent>
            <extension base="tns:Flower-type">
                <sequence>
                    <element name="feeding-frequency" type="string" />
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <simpleType name="Soil">
        <restriction base="string">
            <enumeration value="loamy"/>
            <enumeration value="podzolic"/>
            <enumeration value="ground"/>
            <enumeration value="lime"/>
            <enumeration value="tree bark"/>
        </restriction>
    </simpleType>

    <simpleType name="Multiplying">
        <restriction base="string">
            <enumeration value="leaves"/>
            <enumeration value="seeds"/>
            <enumeration value="cuttings"/>
            <enumeration value="vegetative"/>
        </restriction>
    </simpleType>

    <complexType name="Growing-tips" mixed="true">
        <sequence>
            <element name="min-temperature" type="double" />
            <element name="lighting" type="string"/>
            <element name="watering" type="string"/>
        </sequence>
    </complexType>

    <complexType name="Visual-parameters" mixed="true">
        <sequence>
            <element name="size" type="double" />
            <element name="inflorescence-color" type="string"/>
        </sequence>
    </complexType>

    <simpleType name="Date-of-planting">
        <restriction base="gYearMonth">
            <pattern value="2[0-9][0-9][0-9]-((0[1-9])|(1[0-2]))"/>
        </restriction>
    </simpleType>

    <simpleType name="Id">
        <restriction base="ID">
            <pattern value="f[0-9]+"/>
        </restriction>
    </simpleType>

</schema>

=== NexaiYlia/xml_task2/src/main/resources/flowers.xml
<?xml version="1.0" encoding="utf-8"?>
<flowers xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
         xs:noNamespaceSchemaLocation="flowers.xsd">
    <rose-flower id="f1" in-stock="false">
        <flower-name>Kazanlik Rose</flower-name>
        <date-of-planting>2020-05</date-of-planting>
        <soil>ground</soil>
        <origin>India</origin>
        <visual-parameters>
            <size>1.5</size>
            <inflorescence-color>red</inflorescence-color>
        </visual-parameters>
        <growing-tips>
            <min-temperature>-10</min-temperature>
            <lighting>light-loving</lighting>
            <watering>twice a week</watering>
        </growing-tips>
        <multiplying>cuttings</multiplying>
        <spikes>true</spikes>
    </rose-flower>
    <rose-flower id="f2" in-stock="true">
        <flower-name>Blanc Meillandecor</flower-name>
        <date-of-planting>2019-04</date-of-planting>
        <soil>loamy</soil>
        <origin>France</origin>
        <visual-parameters>
            <size>1.1</size>
            <inflorescence-color>white</inflorescence-color>
        </visual-parameters>
        <growing-tips>
            <min-temperature>-5</min-temperature>
            <lighting>light-loving</lighting>
            <watering>once a week</watering>>
        </growing-tips>
        <multiplying>seeds</multiplying>
        <spikes>true</spikes>
    </rose-flower>
    <rose-flower id="f3" in-stock="true">
        <flower-name>Swany</flower-name>
        <date-of-planting>2021-06</date-of-planting>
        <soil>ground</soil>
        <origin>France</origin>
        <visual-parameters>
            <size>1.2</size>
            <inflorescence-color>pink</inflorescence-color>
        </visual-parameters>
        <growing-tips>
            <min-temperature>-15</min-temperature>
            <lighting>moderate-lighting</lighting>
            <watering>every day</watering>>
        </growing-tips>
        <multiplying>seeds</multiplying>
        <spikes>false</spikes>
    </rose-flower>
    <rose-flower id="f4" in-stock="true">
        <flower-name>Floribunda</flower-name>
        <date-of-planting>2021-07</date-of-planting>
        <soil>ground</soil>
        <origin>Spain</origin>
        <visual-parameters>
            <size>0.65</size>
            <inflorescence-color>purple</inflorescence-color>
        </visual-parameters>
        <growing-tips>
            <min-temperature>-20</min-temperature>
            <lighting>light-loving</lighting>
            <watering>twice a week</watering>>
        </growing-tips>
        <multiplying>leaves</multiplying>
        <spikes>true</spikes>
    </rose-flower>
    <pion-flower id="f5" in-stock="true">
        <flower-name>Aritina Nozen Glory</flower-name>
        <date-of-planting>2020-09</date-of-planting>
        <soil>lime</soil>
        <origin>France</origin>
        <visual-parameters>
            <size>0.7</size>
            <inflorescence-color>pink</inflorescence-color>
        </visual-parameters>
        <growing-tips>
            <min-temperature>-10</min-temperature>
            <lighting>light-loving</lighting>
            <watering>every day</watering>>
        </growing-tips>
        <multiplying>leaves</multiplying>
        <number-peduncles>5</number-peduncles>
    </pion-flower>
    <pion-flower id="f6" in-stock="true">
        <flower-name>Ann Berry Cousins</flower-name>
        <date-of-planting>2019-07</date-of-planting>
        <soil>ground</soil>
        <origin>China</origin>
        <visual-parameters>
            <size>0.95</size>
            <inflorescence-color>coral pink</inflorescence-color>
        </visual-parameters>
        <growing-tips>
            <min-temperature>-10</min-temperature>
            <lighting>low-light</lighting>
            <watering>every day</watering>>
        </growing-tips>
        <multiplying>cuttings</multiplying>
        <number-peduncles>7</number-peduncles>
    </pion-flower>
    <pion-flower id="f7" in-stock="true">
        <flower-name>White Cap</flower-name>
        <date-of-planting>2019-05</date-of-planting>
        <soil>loamy</soil>
        <origin>USA</origin>
        <visual-parameters>
            <size>0.65</size>
            <inflorescence-color>white</inflorescence-color>
        </visual-parameters>
        <growing-tips>
            <min-temperature>0</min-temperature>
            <lighting>low-light</lighting>
            <watering>every day</watering>>
        </growing-tips>
        <multiplying>cuttings</multiplying>
        <number-peduncles>8</number-peduncles>
    </pion-flower>
    <pion-flower id="f8" in-stock="true">
        <flower-name>Treelike</flower-name>
        <date-of-planting>2018-04</date-of-planting>
        <soil>loamy</soil>
        <origin>China</origin>
        <visual-parameters>
            <size>0.8</size>
            <inflorescence-color>white</inflorescence-color>
        </visual-parameters>
        <growing-tips>
            <min-temperature>-10</min-temperature>
            <lighting>low-light</lighting>
            <watering>twice a week</watering>>
        </growing-tips>
        <multiplying>cuttings</multiplying>
        <number-peduncles>5</number-peduncles>
    </pion-flower>
    <rose-flower id="f9" in-stock="true">
        <flower-name>Old Faithful</flower-name>
        <date-of-planting>2021-05</date-of-planting>
        <soil>lime</soil>
        <origin>USA</origin>
        <visual-parameters>
            <size>1.5</size>
            <inflorescence-color>pink</inflorescence-color>
        </visual-parameters>
        <growing-tips>
            <min-temperature>0</min-temperature>
            <lighting>shaded-light</lighting>
            <watering>once a week</watering>>
        </growing-tips>
        <multiplying>seeds</multiplying>
        <spikes>true</spikes>
    </rose-flower>
    <rose-flower id="f10" in-stock="true">
        <flower-name>Dauricum</flower-name>
        <date-of-planting>2020-03</date-of-planting>
        <soil>ground</soil>
        <origin>China</origin>
        <visual-parameters>
            <size>0.5</size>
            <inflorescence-color>red</inflorescence-color>
        </visual-parameters>
        <growing-tips>
            <min-temperature>0</min-temperature>
            <lighting>shaded-light</lighting>
            <watering>once a week</watering>>
        </growing-tips>
        <multiplying>seeds</multiplying>
        <spikes>true</spikes>
    </rose-flower>
    <pion-flower id="f12" in-stock="true">
        <flower-name>Biphrenaria</flower-name>
        <date-of-planting>2018-01</date-of-planting>
        <soil>tree bark</soil>
        <origin>Spain</origin>
        <visual-parameters>
            <size>1</size>
            <inflorescence-color>yellow</inflorescence-color>
        </visual-parameters>
        <growing-tips>
            <min-temperature>5</min-temperature>
            <lighting>light-loving</lighting>
            <watering>once a week</watering>>
        </growing-tips>
        <multiplying>cuttings</multiplying>
        <number-peduncles>8</number-peduncles>
    </pion-flower>
    <pion-flower id="f13" in-stock="true">
        <flower-name>Sesame</flower-name>
        <date-of-planting>2019-08</date-of-planting>
        <soil>tree bark</soil>
        <origin>Netherlands</origin>
        <visual-parameters>
            <size>0.5</size>
            <inflorescence-color>brindle</inflorescence-color>
        </visual-parameters>
        <growing-tips>
            <min-temperature>0</min-temperature>
            <lighting>light-loving</lighting>
            <watering>once a week</watering>>
        </growing-tips>
        <multiplying>cuttings</multiplying>
        <number-peduncles>8</number-peduncles>
    </pion-flower>
    <pion-flower id="f14" in-stock="true">
        <flower-name>Wanda</flower-name>
        <date-of-planting>2021-12</date-of-planting>
        <soil>tree bark</soil>
        <origin>South America</origin>
        <visual-parameters>
            <size>0.5</size>
            <inflorescence-color>orange</inflorescence-color>
        </visual-parameters>
        <growing-tips>
            <min-temperature>18</min-temperature>
            <lighting>light-loving</lighting>
            <watering>twice a week</watering>>
        </growing-tips>
        <multiplying>seeds</multiplying>
        <number-peduncles>8</number-peduncles>
    </pion-flower>
    <pion-flower id="f15" in-stock="true">
        <flower-name>Wanda</flower-name>
        <date-of-planting>2021-12</date-of-planting>
        <soil>ground</soil>
        <origin>Austria</origin>
        <visual-parameters>
            <size>0.6</size>
            <inflorescence-color>green</inflorescence-color>
        </visual-parameters>
        <growing-tips>
            <min-temperature>18</min-temperature>
            <lighting>light-loving</lighting>
            <watering>twice a week</watering>>
        </growing-tips>
        <multiplying>cuttings</multiplying>
        <number-peduncles>8</number-peduncles>
    </pion-flower>
    <pion-flower id="f16" in-stock="true">
        <flower-name>Cattleya</flower-name>
        <date-of-planting>2021-08</date-of-planting>
        <soil>tree bark</soil>
        <origin>Netherlands</origin>
        <visual-parameters>
            <size>0.8</size>
            <inflorescence-color>white</inflorescence-color>
        </visual-parameters>
        <growing-tips>
            <min-temperature>12</min-temperature>
            <lighting>light-loving</lighting>
            <watering>twice a week</watering>>
        </growing-tips>
        <multiplying>cuttings</multiplying>
        <number-peduncles>8</number-peduncles>
    </pion-flower>
</flowers>

=== NexaiYlia/xml_task2/src/test/java/resources/flowers.xml
<?xml version="1.0" encoding="utf-8"?>
<flowers xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
         xs:noNamespaceSchemaLocation="flowers.xsd">
    <rose-flower id="f51" in-stock="false">
        <flower-name>Kazanlik Rose</flower-name>
        <date-of-planting>2020-05</date-of-planting>
        <soil>ground</soil>
        <origin>India</origin>
        <visual-parameters>
            <size>1.5</size>
            <inflorescence-color>red</inflorescence-color>
        </visual-parameters>
        <growing-tips>
            <min-temperature>-10</min-temperature>
            <lighting>light-loving</lighting>
            <watering>twice a week</watering>
        </growing-tips>
        <multiplying>cuttings</multiplying>
        <spikes>true</spikes>
    </rose-flower>

    <pion-flower id="f55" in-stock="true">
        <flower-name>Cattleya</flower-name>
        <date-of-planting>2021-08</date-of-planting>
        <soil>tree bark</soil>
        <origin>Netherlands</origin>
        <visual-parameters>
            <size>0.8</size>
            <inflorescence-color>white</inflorescence-color>
        </visual-parameters>
        <growing-tips>
            <min-temperature>12</min-temperature>
            <lighting>light-loving</lighting>
            <watering>twice a week</watering>>
        </growing-tips>
        <multiplying>cuttings</multiplying>
        <number-peduncles>8</number-peduncles>
    </pion-flower>
</flowers>
